# Generated by Django 5.2.1 on 2025-06-26 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0002_alter_boardmodel_is_archived'),
        ('team', '0003_alter_teammodel_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('task_create', 'Task created'), ('task_update', 'Task updated'), ('task_delete', 'Task deleted'), ('board_create', 'Board created'), ('board_update', 'Board updated'), ('board_archive', 'Board archived/restore'), ('team_member_add', 'Team member added'), ('team_member_drop', 'Team member removed')], max_length=32, verbose_name='Event')),
                ('target_id', models.UUIDField()),
                ('target_repr', models.CharField(max_length=255)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='board.boardmodel', verbose_name='Board')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='team.teammodel', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'ordering': ('-created_at',),
            },
        ),
    ]
