# Generated by Django 5.2.1 on 2025-07-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentrymodel',
            name='event',
            field=models.CharField(choices=[('task_create', 'Task created'), ('task_update', 'Task updated'), ('task_delete', 'Task deleted'), ('board_create', 'Board created'), ('board_update', 'Board updated'), ('board_archive', 'Board archived/restore'), ('team_member_add', 'Team member added'), ('team_member_drop', 'Team member removed'), ('user_signup', 'User signed up'), ('user_login', 'User logged in'), ('user_logout', 'User logged out'), ('profile_update', 'Profile updated')], max_length=32, verbose_name='Event'),
        ),
    ]
