# Generated by Django 5.2.1 on 2025-06-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Archived'),
        ),
    ]
