# Generated by Django 5.2.1 on 2025-05-17 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_national_id_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_number_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(default=1, max_length=11, unique=True, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(9)], verbose_name='National id'),
            preserve_default=False,
        ),
    ]
