# Generated by Django 5.2.1 on 2025-07-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='to_user',
        ),
    ]
